services:
  app-proxy:
    container_name: proxy
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '5000:5000'
    depends_on:
      - app-client

  app-client:
    container_name: client
    build: .
    ports:
      - '5173:5173'
